<a href="https://colab.research.google.com/github/MdShajalalsojib/Machine-Learning-Lab/blob/main/%20Ford%20dimension.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#IMPORT LIBRARY
import pandas as pd

In [2]:
#Empty df
df = pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [6]:
student = ['Md.Shajalal','Md.Sakib','Md.Kacham','Md.Ikbal']

In [7]:
student

['Md.Shajalal', 'Md.Sakib', 'Md.Kacham', 'Md.Ikbal']

In [8]:
df = pd.DataFrame(student)
df

             0
0  Md.Shajalal
1     Md.Sakib
2    Md.Kacham
3     Md.Ikbal

In [9]:
type(df)

pandas.core.frame.DataFrame

In [10]:
type(student)

list

In [11]:
row, col = df.shape

In [12]:
row

4

In [13]:
col

1

In [14]:
df = pd.DataFrame(student, columns=['student_in_Name'])
df

  student_in_Name
0     Md.Shajalal
1        Md.Sakib
2       Md.Kacham
3        Md.Ikbal

In [16]:
df = pd.DataFrame(student, columns=['student_in_Name'])
df

  student_in_Name
0     Md.Shajalal
1        Md.Sakib
2       Md.Kacham
3        Md.Ikbal

In [17]:
df = pd.DataFrame(student, columns=['student_in_Name'], index = ['A','B','C','D'])
df

  student_in_Name
A     Md.Shajalal
B        Md.Sakib
C       Md.Kacham
D        Md.Ikbal

In [18]:
student2 = ['101','102','103','104']
df2 = pd.DataFrame(zip(student,student2), columns=['student_in_Name','student_ID'])

In [23]:
student4 = ['Md. Abdul Kasem','Md. Lokman','Md. Solman','Md. Koim']
df4 = pd.DataFrame(zip(student,student2,student4), columns=['student_in_Name','student_ID', 'student_Father_Name'])

In [24]:
df4

  student_in_Name student_ID student_Father_Name
0     Md.Shajalal        101     Md. Abdul Kasem
1        Md.Sakib        102          Md. Lokman
2       Md.Kacham        103          Md. Solman
3        Md.Ikbal        104            Md. Koim

In [30]:
student3 = ['Bangla','Software','Mathematics','Chemistry']
df3 = pd.DataFrame(zip(student,student2,student3,student4), columns=['student_in_Name','student_ID', 'Subject' ,'student_Father_Name' ])

In [31]:
df3

  student_in_Name student_ID      Subject student_Father_Name
0     Md.Shajalal        101       Bangla     Md. Abdul Kasem
1        Md.Sakib        102     Software          Md. Lokman
2       Md.Kacham        103  Mathematics          Md. Solman
3        Md.Ikbal        104    Chemistry            Md. Koim

In [28]:
df4

  student_in_Name student_ID student_Father_Name
0     Md.Shajalal        101     Md. Abdul Kasem
1        Md.Sakib        102          Md. Lokman
2       Md.Kacham        103          Md. Solman
3        Md.Ikbal        104            Md. Koim

In [29]:
df3

  student_in_Name student_ID          Subject student_Father_Name
0     Md.Shajalal        101  Md. Abdul Kasem              Bangla
1        Md.Sakib        102       Md. Lokman            Software
2       Md.Kacham        103       Md. Solman         Mathematics
3        Md.Ikbal        104         Md. Koim           Chemistry

In [19]:
df2

  student_in_Name student_ID
0     Md.Shajalal        101
1        Md.Sakib        102
2       Md.Kacham        103
3        Md.Ikbal        104

In [26]:
df3

  student_in_Name student_ID          Subject student_Father_Name
0     Md.Shajalal        101  Md. Abdul Kasem     Md. Abdul Kasem
1        Md.Sakib        102       Md. Lokman          Md. Lokman
2       Md.Kacham        103       Md. Solman          Md. Solman
3        Md.Ikbal        104         Md. Koim            Md. Koim

In [5]:
student

{'Md.Ikbal', 'Md.Kacham', 'Md.Sakib', 'Md.Shajalal'}

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Empty DataFrame

In [36]:
stud = [['Md.shjalal', '101','English','A+'],['Md.sojib', '102','Bangla','A-'],['Md.sakib', '103','English','A'],['Md.Nazmul', '104','Softwar','A-'],['Md.Ashraful', '105','Maths','A']]

In [33]:
stud

[['Md.shjalal', '101', 'English', 'A+'],
 ['Md.sojib', '102', 'Bangla', 'A-'],
 ['Md.sakib', '103', 'English', 'A']]

In [34]:
so = pd.DataFrame(stud, columns=['studentName','studentID','Subject','CGPA'])

In [35]:
so

  studentName studentID  Subject CGPA
0  Md.shjalal       101  English   A+
1    Md.sojib       102   Bangla   A-
2    Md.sakib       103  English    A

In [37]:
so

  studentName studentID  Subject CGPA
0  Md.shjalal       101  English   A+
1    Md.sojib       102   Bangla   A-
2    Md.sakib       103  English    A

In [38]:
soj = pd.DataFrame(stud, columns=['studentName','studentID','Subject','CGPA'])

In [39]:
soj

   studentName studentID  Subject CGPA
0   Md.shjalal       101  English   A+
1     Md.sojib       102   Bangla   A-
2     Md.sakib       103  English    A
3    Md.Nazmul       104  Softwar   A-
4  Md.Ashraful       105    Maths    A