<a href="https://colab.research.google.com/github/MdShajalalsojib/Machine-Learning-Lab/blob/main/FileNumber3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
sh = pd.read_csv('points_table.csv')

In [3]:
sh

,position,team,matches,wins,defeats,ties,abandoned,points,nrr
0,1,Rajasthan Royals,1,1,0,0,0,2,4.171
1,2,Royal Challengers Bengaluru,1,1,0,0,0,2,22.907
2,3,Delhi Capitals,1,1,0,0,0,2,1.397
3,4,Mumbai Indians,1,1,0,0,0,2,0.687
4,5,Punjab Kings,1,1,0,0,0,2,0.509
5,6,Sunrisers Hyderabad,2,1,1,0,0,2,0.469
6,7,Gujarat Titans,1,0,1,0,0,0,-0.509
7,8,Lucknow Super Giants,1,0,1,0,0,0,-1.397
8,9,Kolkata Knight Riders,2,0,1,0,0,0,-1.964
9,10,Chennai Super Kings,1,0,1,0,0,0,-4.171

In [4]:
sh.head()

,position,team,matches,wins,defeats,ties,abandoned,points,nrr
0,1,Rajasthan Royals,1,1,0,0,0,2,4.171
1,2,Royal Challengers Bengaluru,1,1,0,0,0,2,22.907
2,3,Delhi Capitals,1,1,0,0,0,2,1.397
3,4,Mumbai Indians,1,1,0,0,0,2,0.687
4,5,Punjab Kings,1,1,0,0,0,2,0.509

In [5]:
sh.shape

(10, 9)

In [7]:
sh.tail()

,position,team,matches,wins,defeats,ties,abandoned,points,nrr
5,6,Sunrisers Hyderabad,2,1,1,0,0,2,0.469
6,7,Gujarat Titans,1,0,1,0,0,0,-0.509
7,8,Lucknow Super Giants,1,0,1,0,0,0,-1.397
8,9,Kolkata Knight Riders,2,0,1,0,0,0,-1.964
9,10,Chennai Super Kings,1,0,1,0,0,0,-4.171

In [8]:
sh.values

array([[1, 'Rajasthan Royals', 1, 1, 0, 0, 0, 2, 4.171],
       [2, 'Royal Challengers Bengaluru', 1, 1, 0, 0, 0, 2, 22.907],
       [3, 'Delhi Capitals', 1, 1, 0, 0, 0, 2, 1.397],
       [4, 'Mumbai Indians', 1, 1, 0, 0, 0, 2, 0.687],
       [5, 'Punjab Kings', 1, 1, 0, 0, 0, 2, 0.509],
       [6, 'Sunrisers Hyderabad', 2, 1, 1, 0, 0, 2, 0.469],
       [7, 'Gujarat Titans', 1, 0, 1, 0, 0, 0, -0.509],
       [8, 'Lucknow Super Giants', 1, 0, 1, 0, 0, 0, -1.397],
       [9, 'Kolkata Knight Riders', 2, 0, 1, 0, 0, 0, -1.964],
       [10, 'Chennai Super Kings', 1, 0, 1, 0, 0, 0, -4.171]],
      dtype=object)

In [9]:
print(sh.values)

[[1 'Rajasthan Royals' 1 1 0 0 0 2 4.171]
 [2 'Royal Challengers Bengaluru' 1 1 0 0 0 2 22.907]
 [3 'Delhi Capitals' 1 1 0 0 0 2 1.397]
 [4 'Mumbai Indians' 1 1 0 0 0 2 0.687]
 [5 'Punjab Kings' 1 1 0 0 0 2 0.509]
 [6 'Sunrisers Hyderabad' 2 1 1 0 0 2 0.469]
 [7 'Gujarat Titans' 1 0 1 0 0 0 -0.509]
 [8 'Lucknow Super Giants' 1 0 1 0 0 0 -1.397]
 [9 'Kolkata Knight Riders' 2 0 1 0 0 0 -1.964]
 [10 'Chennai Super Kings' 1 0 1 0 0 0 -4.171]]

In [10]:
sh.columns

Index(['position', 'team', 'matches', 'wins', 'defeats', 'ties', 'abandoned',
       'points', 'nrr'],
      dtype='object')

In [11]:
sh.index

RangeIndex(start=0, stop=10, step=1)

In [12]:
sh.head(7)

,position,team,matches,wins,defeats,ties,abandoned,points,nrr
0,1,Rajasthan Royals,1,1,0,0,0,2,4.171
1,2,Royal Challengers Bengaluru,1,1,0,0,0,2,22.907
2,3,Delhi Capitals,1,1,0,0,0,2,1.397
3,4,Mumbai Indians,1,1,0,0,0,2,0.687
4,5,Punjab Kings,1,1,0,0,0,2,0.509
5,6,Sunrisers Hyderabad,2,1,1,0,0,2,0.469
6,7,Gujarat Titans,1,0,1,0,0,0,-0.509

In [13]:
sh.team

0               Rajasthan Royals
1    Royal Challengers Bengaluru
2                 Delhi Capitals
3                 Mumbai Indians
4                   Punjab Kings
5            Sunrisers Hyderabad
6                 Gujarat Titans
7           Lucknow Super Giants
8          Kolkata Knight Riders
9            Chennai Super Kings
Name: team, dtype: object

In [14]:
sh.team.head(5)

0               Rajasthan Royals
1    Royal Challengers Bengaluru
2                 Delhi Capitals
3                 Mumbai Indians
4                   Punjab Kings
Name: team, dtype: object

In [15]:
sh[['team','matches']].head()

                          team  matches
0             Rajasthan Royals        1
1  Royal Challengers Bengaluru        1
2               Delhi Capitals        1
3               Mumbai Indians        1
4                 Punjab Kings        1

In [16]:
sh[['team','matches','points']].head(4)

                          team  matches  points
0             Rajasthan Royals        1       2
1  Royal Challengers Bengaluru        1       2
2               Delhi Capitals        1       2
3               Mumbai Indians        1       2

In [17]:
sh['nrr'].sort_values()

9    -4.171
8    -1.964
7    -1.397
6    -0.509
5     0.469
4     0.509
3     0.687
2     1.397
0     4.171
1    22.907
Name: nrr, dtype: float64

In [18]:
sh['team'].sort_values()

9            Chennai Super Kings
2                 Delhi Capitals
6                 Gujarat Titans
8          Kolkata Knight Riders
7           Lucknow Super Giants
3                 Mumbai Indians
4                   Punjab Kings
0               Rajasthan Royals
1    Royal Challengers Bengaluru
5            Sunrisers Hyderabad
Name: team, dtype: object

In [20]:
sh.head()

,position,team,matches,wins,defeats,ties,abandoned,points,nrr
0,1,Rajasthan Royals,1,1,0,0,0,2,4.171
1,2,Royal Challengers Bengaluru,1,1,0,0,0,2,22.907
2,3,Delhi Capitals,1,1,0,0,0,2,1.397
3,4,Mumbai Indians,1,1,0,0,0,2,0.687
4,5,Punjab Kings,1,1,0,0,0,2,0.509

In [21]:
sh['position'].sort_values()

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: position, dtype: int64

In [23]:
sh['nrr'].sort_values(ascending=False)

1    22.907
0     4.171
2     1.397
3     0.687
4     0.509
5     0.469
6    -0.509
7    -1.397
8    -1.964
9    -4.171
Name: nrr, dtype: float64

In [25]:
sh.sort_values('points',ascending=False)

,position,team,matches,wins,defeats,ties,abandoned,points,nrr
0,1,Rajasthan Royals,1,1,0,0,0,2,4.171
1,2,Royal Challengers Bengaluru,1,1,0,0,0,2,22.907
2,3,Delhi Capitals,1,1,0,0,0,2,1.397
3,4,Mumbai Indians,1,1,0,0,0,2,0.687
4,5,Punjab Kings,1,1,0,0,0,2,0.509
5,6,Sunrisers Hyderabad,2,1,1,0,0,2,0.469
6,7,Gujarat Titans,1,0,1,0,0,0,-0.509
7,8,Lucknow Super Giants,1,0,1,0,0,0,-1.397
8,9,Kolkata Knight Riders,2,0,1,0,0,0,-1.964
9,10,Chennai Super Kings,1,0,1,0,0,0,-4.171

In [26]:
sh.sort_values('points',ascending=False)

,position,team,matches,wins,defeats,ties,abandoned,points,nrr
0,1,Rajasthan Royals,1,1,0,0,0,2,4.171
1,2,Royal Challengers Bengaluru,1,1,0,0,0,2,22.907
2,3,Delhi Capitals,1,1,0,0,0,2,1.397
3,4,Mumbai Indians,1,1,0,0,0,2,0.687
4,5,Punjab Kings,1,1,0,0,0,2,0.509
5,6,Sunrisers Hyderabad,2,1,1,0,0,2,0.469
6,7,Gujarat Titans,1,0,1,0,0,0,-0.509
7,8,Lucknow Super Giants,1,0,1,0,0,0,-1.397
8,9,Kolkata Knight Riders,2,0,1,0,0,0,-1.964
9,10,Chennai Super Kings,1,0,1,0,0,0,-4.171

In [27]:
sh.sort_values('points',ascending=False)

,position,team,matches,wins,defeats,ties,abandoned,points,nrr
0,1,Rajasthan Royals,1,1,0,0,0,2,4.171
1,2,Royal Challengers Bengaluru,1,1,0,0,0,2,22.907
2,3,Delhi Capitals,1,1,0,0,0,2,1.397
3,4,Mumbai Indians,1,1,0,0,0,2,0.687
4,5,Punjab Kings,1,1,0,0,0,2,0.509
5,6,Sunrisers Hyderabad,2,1,1,0,0,2,0.469
6,7,Gujarat Titans,1,0,1,0,0,0,-0.509
7,8,Lucknow Super Giants,1,0,1,0,0,0,-1.397
8,9,Kolkata Knight Riders,2,0,1,0,0,0,-1.964
9,10,Chennai Super Kings,1,0,1,0,0,0,-4.171