<a href="https://colab.research.google.com/github/MdShajalalsojib/Machine-Learning-Lab/blob/main/Lab_Report_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Data cleaningt**

In [1]:
import numpy as np
import pandas as pd

In [4]:
sojib = pd.read_csv('bangla_spam.csv')

In [5]:
sojib.head()

   type                                               text
0  spam  এই মেসেজটি শেয়ার করুন এবং জিতে নিন আকর্ষণীয় ...
1  spam  আপনার বন্ধুদের রেফার করুন এবং প্রতি রেফারেলে ২...
2   ham  ট্রানজ্যাকশন নম্বর R234321.1554.640085 20 টাকা...
3  spam  নতুন অফার! সীমিত সময়ের জন্য পণ্যের উপর ৯০% পর...
4   ham  নববর্ষের শুভেচ্ছা!! আল্লাহ আপনার সকল কষ্ট দূর ...

In [6]:
sojib.dropna(inplace=True)

In [7]:
import re

def clean_text(text):
    text = re.sub(r'[^\u0980-\u09FF\s]', '', str(text))
    return text

sojib['clean_text'] = sojib['text'].apply(clean_text)

sojib[['text','clean_text']].head()

,text,clean_text
0,এই মেসেজটি শেয়ার করুন এবং জিতে নিন আকর্ষণীয় ...,এই মেসেজটি শেয়ার করুন এবং জিতে নিন আকর্ষণীয় ...
1,আপনার বন্ধুদের রেফার করুন এবং প্রতি রেফারেলে ২...,আপনার বন্ধুদের রেফার করুন এবং প্রতি রেফারেলে ২...
2,ট্রানজ্যাকশন নম্বর R234321.1554.640085 20 টাকা...,ট্রানজ্যাকশন নম্বর টাকা রিচার্জটি সফল হয়েছে ...
3,নতুন অফার! সীমিত সময়ের জন্য পণ্যের উপর ৯০% পর...,নতুন অফার সীমিত সময়ের জন্য পণ্যের উপর ৯০ পর্য...
4,নববর্ষের শুভেচ্ছা!! আল্লাহ আপনার সকল কষ্ট দূর ...,নববর্ষের শুভেচ্ছা আল্লাহ আপনার সকল কষ্ট দূর কর...

In [8]:
sojib['tokens'] = sojib['clean_text'].apply(lambda x: x.split())

sojib[['clean_text','tokens']].head()

,clean_text,tokens
0,এই মেসেজটি শেয়ার করুন এবং জিতে নিন আকর্ষণীয় ...,"[এই, মেসেজটি, শেয়ার, করুন, এবং, জিতে, নিন, আক..."
1,আপনার বন্ধুদের রেফার করুন এবং প্রতি রেফারেলে ২...,"[আপনার, বন্ধুদের, রেফার, করুন, এবং, প্রতি, রেফ..."
2,ট্রানজ্যাকশন নম্বর টাকা রিচার্জটি সফল হয়েছে ...,"[ট্রানজ্যাকশন, নম্বর, টাকা, রিচার্জটি, সফল, হয়..."
3,নতুন অফার সীমিত সময়ের জন্য পণ্যের উপর ৯০ পর্য...,"[নতুন, অফার, সীমিত, সময়ের, জন্য, পণ্যের, উপর,..."
4,নববর্ষের শুভেচ্ছা আল্লাহ আপনার সকল কষ্ট দূর কর...,"[নববর্ষের, শুভেচ্ছা, আল্লাহ, আপনার, সকল, কষ্ট,..."

In [9]:
stopwords = ['আমি','তুমি','এই','ওই','সে','এটা']

sojib['tokens'] = sojib['tokens'].apply(lambda x: [word for word in x if word not in stopwords])

sojib[['tokens']].head()

                                              tokens
0  [মেসেজটি, শেয়ার, করুন, এবং, জিতে, নিন, আকর্ষণ...
1  [আপনার, বন্ধুদের, রেফার, করুন, এবং, প্রতি, রেফ...
2  [ট্রানজ্যাকশন, নম্বর, টাকা, রিচার্জটি, সফল, হয়...
3  [নতুন, অফার, সীমিত, সময়ের, জন্য, পণ্যের, উপর,...
4  [নববর্ষের, শুভেচ্ছা, আল্লাহ, আপনার, সকল, কষ্ট,...

In [10]:
def stemming(words):
    return [word[:-1] if len(word) > 4 else word for word in words]

sojib['final'] = sojib['tokens'].apply(stemming)

sojib[['final']].head()

                                               final
0  [মেসেজট, শেয়া, করুন, এবং, জিতে, নিন, আকর্ষণীয...
1  [আপনা, বন্ধুদে, রেফা, করুন, এবং, প্রত, রেফারেল...
2  [ট্রানজ্যাকশ, নম্ব, টাকা, রিচার্জট, সফল, হয়েছ,...
3  [নতুন, অফার, সীমি, সময়ে, জন্য, পণ্যে, উপর, ৯০...
4  [নববর্ষে, শুভেচ্ছ, আল্লা, আপনা, সকল, কষ্ট, দূর...

In [11]:
sojib.to_csv("cleaned_dataset.csv", index=False)

In [12]:
import os
os.listdir()

['.config', 'bangla_spam.csv', 'cleaned_dataset.csv', 'sample_data']