<a href="https://colab.research.google.com/github/MdShajalalsojib/Machine-Learning-Lab/blob/main/Lab_Report_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pdp

In [4]:
 so = pdp.read_csv('bangla_spam.csv')

In [5]:
so.head()

   type                                               text
0  spam  এই মেসেজটি শেয়ার করুন এবং জিতে নিন আকর্ষণীয় ...
1  spam  আপনার বন্ধুদের রেফার করুন এবং প্রতি রেফারেলে ২...
2   ham  ট্রানজ্যাকশন নম্বর R234321.1554.640085 20 টাকা...
3  spam  নতুন অফার! সীমিত সময়ের জন্য পণ্যের উপর ৯০% পর...
4   ham  নববর্ষের শুভেচ্ছা!! আল্লাহ আপনার সকল কষ্ট দূর ...

In [6]:
so.head(10)

   type                                               text
0  spam  এই মেসেজটি শেয়ার করুন এবং জিতে নিন আকর্ষণীয় ...
1  spam  আপনার বন্ধুদের রেফার করুন এবং প্রতি রেফারেলে ২...
2   ham  ট্রানজ্যাকশন নম্বর R234321.1554.640085 20 টাকা...
3  spam  নতুন অফার! সীমিত সময়ের জন্য পণ্যের উপর ৯০% পর...
4   ham  নববর্ষের শুভেচ্ছা!! আল্লাহ আপনার সকল কষ্ট দূর ...
5  spam  আপনার ইমেইল যাচাই করুন এবং ২০০০ টাকা বোনাস জিতুন!
6  spam         নতুন গ্যাজেট কিনুন এবং ১০% ক্যাশব্যাক পান!
7  spam  আপনার মোবাইল রিচার্জ করুন এবং ১৫% ক্যাশব্যাক পান!
8  spam   বিশেষ ছাড়! সব পণ্যের উপর ৯৫% পর্যন্ত ডিসকাউন্ট!
9  spam                আজই ক্লিক করুন এবং ৫০০০ টাকা জিতুন!

In [7]:
import re

def clean_text(text):
    text = re.sub(r'[^\u0980-\u09FF\s]', '', str(text))
    return text

so['clean_text'] = so['text'].apply(clean_text)

so['tokens'] = so['clean_text'].apply(lambda x: x.split())

stopwords = ['আমি','তুমি','এই','ওই','সে','এটা']
so['tokens'] = so['tokens'].apply(lambda x: [word for word in x if word not in stopwords])

def stemming(words):
    return [word[:-1] if len(word) > 4 else word for word in words]

so['final'] = so['tokens'].apply(stemming)

so['final_text'] = so['final'].apply(lambda x: " ".join(x))

In [8]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()
X = tfidf.fit_transform(so['final_text'])

In [9]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y = le.fit_transform(so['type'])

In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [11]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train, y_train)

MultinomialNB()

In [12]:
from sklearn.metrics import accuracy_score

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.8963531669865643