<a href="https://colab.research.google.com/github/MdShajalalsojib/Machine-Learning-Lab/blob/main/Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('housing.csv')

In [3]:
df.head()

,Avg. Area Income,Avg. Area House Age,Avg. Area Number of Rooms,Avg. Area Number of Bedrooms,Area Population,Price,Address
0,79545.45857,5.682861,7.009188,4.09,23086.80050,1.059034e+06,"208 Michael Ferry Apt. 674\nLaurabury, NE 3701..."
1,79248.64245,6.002900,6.730821,3.09,40173.07217,1.505891e+06,"188 Johnson Views Suite 079\nLake Kathleen, CA..."
2,61287.06718,5.865890,8.512727,5.13,36882.15940,1.058988e+06,"9127 Elizabeth Stravenue\nDanieltown, WI 06482..."
3,63345.24005,7.188236,5.586729,3.26,34310.24283,1.260617e+06,USS Barnett\nFPO AP 44820
4,59982.19723,5.040555,7.839388,4.23,26354.10947,6.309435e+05,USNS Raymond\nFPO AE 09386

In [4]:
df.head(20)

,Avg. Area Income,Avg. Area House Age,Avg. Area Number of Rooms,Avg. Area Number of Bedrooms,Area Population,Price,Address
0,79545.45857,5.682861,7.009188,4.09,23086.80050,1.059034e+06,"208 Michael Ferry Apt. 674\nLaurabury, NE 3701..."
1,79248.64245,6.002900,6.730821,3.09,40173.07217,1.505891e+06,"188 Johnson Views Suite 079\nLake Kathleen, CA..."
2,61287.06718,5.865890,8.512727,5.13,36882.15940,1.058988e+06,"9127 Elizabeth Stravenue\nDanieltown, WI 06482..."
3,63345.24005,7.188236,5.586729,3.26,34310.24283,1.260617e+06,USS Barnett\nFPO AP 44820
4,59982.19723,5.040555,7.839388,4.23,26354.10947,6.309435e+05,USNS Raymond\nFPO AE 09386
5,80175.75416,4.988408,6.104512,4.04,26748.42842,1.068138e+06,"06039 Jennifer Islands Apt. 443\nTracyport, KS..."
6,64698.46343,6.025336,8.147760,3.41,60828.24909,1.502056e+06,"4759 Daniel Shoals Suite 442\nNguyenburgh, CO ..."
7,78394.33928,6.989780,6.620478,2.42,36516.35897,1.573937e+06,"972 Joyce Viaduct\nLake William, TN 17778-6483"
8,59927.66081,5.362126,6.393121,2.30,29387.39600,7.988695e+05,USS Gilbert\nFPO AA 20957
9,81885.92718,4.423672,8.167688,6.10,40149.96575,1.545155e+06,Unit 9446 Box 0958\nDPO AE 97025
10,80527.47208,8.093513,5.042747,4.10,47224.35984,1.707046e+06,"6368 John Motorway Suite 700\nJanetbury, NM 26854"
11,50593.69550,4.496513,7.467627,4.49,34343.99189,6.637324e+05,"911 Castillo Park Apt. 717\nDavisborough, PW 7..."
12,39033.80924,7.671755,7.250029,3.10,39220.36147,1.042814e+06,"209 Natasha Stream Suite 961\nHuffmanland, NE ..."
13,73163.66344,6.919535,5.993188,2.27,32326.12314,1.291332e+06,"829 Welch Track Apt. 992\nNorth John, AR 26532..."
14,69391.38018,5.344776,8.406418,4.37,35521.29403,1.402818e+06,"PSC 5330, Box 4420\nAPO AP 08302"
15,73091.86675,5.443156,8.517513,4.01,23929.52405,1.306675e+06,"2278 Shannon View\nNorth Carriemouth, NM 84617"
16,79706.96306,5.067890,8.219771,3.12,39717.81358,1.556787e+06,"064 Hayley Unions\nNicholsborough, HI 44161-1887"
17,61929.07702,4.788550,5.097010,4.30,24595.90150,5.284852e+05,"5498 Rachel Locks\nNew Gregoryshire, PW 54755"
18,63508.19430,5.947165,7.187774,5.12,35719.65305,1.019426e+06,Unit 7424 Box 2786\nDPO AE 71255
19,62085.27640,5.739411,7.091808,5.49,44922.10670,1.030591e+06,"19696 Benjamin Cape\nStephentown, ME 36952-4733"

In [5]:
# do one-hot encoding for all categorical columns
df_encoded = pd.get_dummies(df, dtype = int)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 7 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Avg. Area Income              5000 non-null   float64
 1   Avg. Area House Age           5000 non-null   float64
 2   Avg. Area Number of Rooms     5000 non-null   float64
 3   Avg. Area Number of Bedrooms  5000 non-null   float64
 4   Area Population               5000 non-null   float64
 5   Price                         5000 non-null   float64
 6   Address                       5000 non-null   object
dtypes: float64(6), object(1)
memory usage: 273.6+ KB

In [7]:
df_encoded.head()

,Avg. Area Income,Avg. Area House Age,Avg. Area Number of Rooms,Avg. Area Number of Bedrooms,Area Population,Price,"Address_000 Adkins Crescent\nSouth Teresa, AS 49642-1348","Address_000 Todd Pines\nAshleyberg, KY 90207-1179","Address_001 Steve Plaza\nJessicastad, UT 25190","Address_0010 Gregory Loaf\nSouth Ericfort, VA 34651-0718",...,Address_Unit 9446 Box 0958\nDPO AE 97025,Address_Unit 9463 Box 0963\nDPO AE 49984-2796,Address_Unit 9494 Box 2307\nDPO AE 58622,Address_Unit 9664 Box 1605\nDPO AA 30902,Address_Unit 9732 Box 1846\nDPO AE 69898-3304,Address_Unit 9774 Box 4511\nDPO AE 44963,Address_Unit 9778 Box 2114\nDPO AP 59374,Address_Unit 9785 Box 0790\nDPO AP 60371-0797,Address_Unit 9831 Box 7128\nDPO AA 54705,Address_Unit 9871 Box 9037\nDPO AP 37275-9289
0,79545.45857,5.682861,7.009188,4.09,23086.80050,1.059034e+06,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,79248.64245,6.002900,6.730821,3.09,40173.07217,1.505891e+06,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,61287.06718,5.865890,8.512727,5.13,36882.15940,1.058988e+06,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,63345.24005,7.188236,5.586729,3.26,34310.24283,1.260617e+06,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,59982.19723,5.040555,7.839388,4.23,26354.10947,6.309435e+05,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [8]:
df_encoded.describe()

,Avg. Area Income,Avg. Area House Age,Avg. Area Number of Rooms,Avg. Area Number of Bedrooms,Area Population,Price,"Address_000 Adkins Crescent\nSouth Teresa, AS 49642-1348","Address_000 Todd Pines\nAshleyberg, KY 90207-1179","Address_001 Steve Plaza\nJessicastad, UT 25190","Address_0010 Gregory Loaf\nSouth Ericfort, VA 34651-0718",...,Address_Unit 9446 Box 0958\nDPO AE 97025,Address_Unit 9463 Box 0963\nDPO AE 49984-2796,Address_Unit 9494 Box 2307\nDPO AE 58622,Address_Unit 9664 Box 1605\nDPO AA 30902,Address_Unit 9732 Box 1846\nDPO AE 69898-3304,Address_Unit 9774 Box 4511\nDPO AE 44963,Address_Unit 9778 Box 2114\nDPO AP 59374,Address_Unit 9785 Box 0790\nDPO AP 60371-0797,Address_Unit 9831 Box 7128\nDPO AA 54705,Address_Unit 9871 Box 9037\nDPO AP 37275-9289
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5.000000e+03,5000.000000,5000.000000,5000.000000,5000.000000,...,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,68583.108984,5.977222,6.987792,3.981330,36163.516039,1.232073e+06,0.000200,0.000200,0.000200,0.000200,...,0.000200,0.000200,0.000200,0.000200,0.000200,0.000200,0.000200,0.000200,0.000200,0.000200
std,10657.991214,0.991456,1.005833,1.234137,9925.650114,3.531176e+05,0.014142,0.014142,0.014142,0.014142,...,0.014142,0.014142,0.014142,0.014142,0.014142,0.014142,0.014142,0.014142,0.014142,0.014142
min,17796.631190,2.644304,3.236194,2.000000,172.610686,1.593866e+04,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,61480.562390,5.322283,6.299250,3.140000,29403.928700,9.975771e+05,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,68804.286405,5.970429,7.002902,4.050000,36199.406690,1.232669e+06,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,75783.338665,6.650808,7.665871,4.490000,42861.290770,1.471210e+06,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,107701.748400,9.519088,10.759588,6.500000,69621.713380,2.469066e+06,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

**make sure to save the encoded DataFrame**

In [9]:

df_encoded.to_csv('df_encoded.csv',index=False)

**find the correlation between features**

In [10]:
corr = df_encoded.corr()

**Visualize the correlation matrix**

In [11]:
import seaborn as sns
import matplotlib.pyplot as plt

#  Heatmap to visualize the correlation matrix

In [ ]:
plt.figure(figsize=(10,10))
sns.heatmap(corr,annot=True,fmt='.1f',linewidths=1,cmap='RdBu')

In [ ]:
# y for target variable, and X for features
y = df_encoded['price']
X = df_encoded.drop('price',axis=1)

In [ ]:
# Split the dataset into training and testing sets
from sklearn.model_selection import train_test_split

In [ ]:
# Cross-validation is a technique used to assess how the results of a statistical analysis will generalize to an independent data set.
# https://www.geeksforgeeks.org/machine-learning/cross-validation-machine-learning/?/
X_train, X_test, y_train, y_test = train_test_split(X,y,train_size=0.8,random_state=5,)

In [ ]:
# Proportion of training data to the entire dataset
len(X_train)/len(df_encoded)

In [ ]:
# Import the Linear Regression model
from sklearn.linear_model import LinearRegression

In [ ]:
# Create an instance of the Linear Regression model
model = LinearRegression()

In [ ]:
# Fit the model to the training data
model.fit(X_train,y_train)

In [ ]:
# Evaluate the model on the test set
model.score(X_test,y_test)

In [ ]:
# Predicting the price of a house with specific features
model.predict([[7420,4,2,3,2,0,1,1,0,1,0,1,0,0,1,0,1,1,0,0]])

In [ ]:
# Coefficients of the model
model.coef_ # m1, m2, ...

In [ ]:
# Intercept of the model
model.intercept_ # c

In [ ]:
# Save the model using joblib
import joblib

In [ ]:
# Save the model to a file
joblib.dump(model,'lr_house_predication_model.joblib')

In [ ]:
# Load the model from the file
old_model = joblib.load('lr_house_predication_model.joblib')

In [ ]:
# verify the loaded model
old_model.score(X_test,y_test)